# The URL the site will be built for
base_url = "https://fufexan.net"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "no-style-please"
title = "~fufexan.net"

[extra]
# Put all your custom variables here

logo = "images/logo.png"

# show navbar
list_pages = true

# disable useless stuff
twitter_card = true

header_nav = [
    { name = "~fufexan.net", url = "/" },
    # { name = "#tags", url = "/tags" },
    # { name = "+categories", url = "/categories" },
    # { name = "@contexts", url = "/contexts" },
    { name = "about", url = "/about/" },
]

footer_nav = [
    { name = "< prev", url = "https://nixwebr.ing/prev/fufexan" },
    { name = "Nix webring", url = "https://nixwebr.ing" },
    { name = "🎲", url = "https://nixwebr.ing/rand" },
    { name = "next >", url = "https://nixwebr.ing/next/fufexan" },
]
